name: CI
on:
  push:
    branches: [ "master", "pre-release" ]
  pull_request:
    branches: [ "master", "pre-release" ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    # Match Dockerfile dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          espeak-ng \
          espeak-ng-data \
          git \
          libsndfile1 \
          curl \
          ffmpeg \
          g++ \
          cmake
    
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Run Tests
      run: |
        uv run --extra test --extra cpu pytest api/tests/ --asyncio-mode=auto --cov=api --cov-report=term-missing --cov-report=xml
    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
